Const-corrected and updated README.md
Awsomedude/easyDialog pull request #7
Opened 2019-04-30 19:34 UTC by AliLogic

2019-04-30 19:35 UTC, Southclaws requested changes

2019-04-30 19:35 UTC, Southclaws commented on README.md
> +Southclaws - for samp-ctl
I hate being pedantic [but this is technically sampctl](https://github.com/Southclaws/sampctl/wiki/What-Does-sampctl-Mean)

2019-05-01 08:46 UTC, AliLogic commented
Users who don't have their a_samp const corrected will warnings, so if anybody has put up the const corrected default libraries, then put up a link here and i'll add it.

2019-05-01 11:42 UTC, AliLogic commented
I've fixed my oofs (errors) and added a warning that users should use sampctl's std lib. If there's anything that I should take care of, please let me know :) Have a nice day.

2019-05-01 14:52 UTC, Southclaws commented
Thank you!

2019-05-01 14:52 UTC, Southclaws approved these changes

2019-05-01 14:52 UTC, merged